# from: https://spring.io/guides/gs/accessing-data-mysql/
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor
  jpa:
    hibernate:
      ddl-auto: create
